services:
  aztebot-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6oFqJERp8X0V9RGN0lfhu80lqAx940
      MYSQL_USER: discordbot1
      MYSQL_DATABASE: aztebotBotDb
      MYSQL_PASSWORD: b21fCTAkaxI1a20utLhkYsMIB1QING
    ports:
      - "3306:3306"

  aztemarket-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6oFqJERp8X0V9RGN0lfhu80lqAx940
      MYSQL_USER: discordbot2
      MYSQL_DATABASE: azteMarketDb
      MYSQL_PASSWORD: b21fCTAkaxI1a20utLhkYsMIB1QING
    ports:
      - "3307:3306"
  
  bot-service:
    container_name: bot-service
    depends_on:
      - aztebot-db
      - aztemarket-db
    env_file:
      ./.env
    build:
      dockerfile: ./cmd/Dockerfile

networks:
  default:
    name: dev_network
    driver: bridge
    external: true