version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  
  bot-service:
    container_name: bot-service
    env_file:
      ./.env
    build:
      dockerfile: ./cmd/bot-service/Dockerfile
    volumes: 
      - "./internal/bot-service/logs:/app/logs"
  
  azteradio-service:
    container_name: azteradio-service
    # env_file:
    #   ./cmd/azteradio-service-rawon/.config.env
    build:
      dockerfile: ./cmd/azteradio-service/Dockerfile

  # aztemusic-service-1:
  #   container_name: aztemusic-service-1
  #   # env_file:
  #   #   ./cmd/aztemusic-service-rawon/1/.config.env
  #   build:
  #     dockerfile: ./cmd/aztemusic-service-new/1/Dockerfile

  # aztemusic-service-1:
  #   container_name: aztemusic-service-1
  #   env_file:
  #     ./.env
  #   build:
  #     dockerfile: ./cmd/aztemusic-service/1/Dockerfile

  # aztemusic-service-2:
  #   container_name: aztemusic-service-2
  #   env_file:
  #     ./.env
  #   build:
  #     dockerfile: ./cmd/aztemusic-service/2/Dockerfile

  # aztemusic-service-3:
  #   container_name: aztemusic-service-3
  #   env_file:
  #     ./.env
  #   build:
  #     dockerfile: ./cmd/aztemusic-service/3/Dockerfile


networks:
  default:
    name: dev_network
    driver: bridge
    external: true