version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  
  bot-service:
    container_name: bot-service
    depends_on:
      - mysql-db
    env_file:
      ./.env
    build:
      dockerfile: ./cmd/Dockerfile
    volumes: 
      - "./logs:/app/logs"

networks:
  default:
    name: dev_network
    driver: bridge
    external: true