version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  
  bot-service:
    container_name: bot-service
    env_file:
      ./.env
    build:
      dockerfile: ./cmd/bot-service/Dockerfile
    volumes: 
      - "./internal/bot-service/logs:/app/logs"

  # azteradio-service:
  #   container_name: azteradio-service
  #   env_file:
  #     ./.env
  #   build:
  #     dockerfile: ./cmd/azteradio-service/Dockerfile
  #   volumes: 
  #     - "./internal/azteradio-service/logs:/app/logs"
  #     - "./downloads:/app/downloads"
  
  azteradio-service-java:
    container_name: azteradio-service-java
    env_file:
      ./.env
    build:
      dockerfile: ./cmd/azteradio-service-java/Dockerfile

networks:
  default:
    name: dev_network
    driver: bridge
    external: true