appName: "AzteRadio"

# Your Discord bot token (Found at https://discord.com/developers/applications)
botToken: "MTE3Mzc4MTY4NTU0NDk1MTkxOA.Gp4BKB.9PbSvir5iEB2Q69vny2mR8sOZ_ny-u3X5usAbA"

# Your Discord bot client ID
clientId: "1173781685544951918"

# Your Genius API client access token (Found at https://genius.com/developers)
geniusApiKey: ""

# The colour to use for embeds sent by the bot
embedColour: "#2B2D31"

# Whether analytics should be sent when starting the bot
# See https://github.com/NerdyTechy/Melody/wiki/Analytics
enableAnalytics: false

# Whether the bot should autocomplete search results
# Disable this if you're experiencing Unknown Interaction errors
enableAutocomplete: false

# Settings to control the bot's player and controller
player:
    # Leave VC when a song ends
    leaveOnEndDelay: 300000 # 5 minutes
    # Leave VC when a song is stopped
    leaveOnStopDelay: 300000 # 5 minutes
    # Leave VC when the channel is empty
    leaveOnEmptyDelay: 1.728e+8 # 48 hours
    # Deafen bot while playing
    deafenBot: true

# The emojis to be used in buttons for certain embeds
# See https://github.com/NerdyTechy/Melody/wiki/Using-Custom-Emojis
emojis:
    stop: "⏹"
    skip: "⏭"
    queue: "📜"
    pause: "⏯"
    lyrics: "📜"
    back: "⏮"

# Make Melody use a proxy when making requests.
# Useful if you're experiencing 429 errors.
# See https://github.com/NerdyTechy/Melody/wiki/Proxying-Requests
# Omit user:pass@ if your proxy does not require authentication.
proxy:
    enable: false
    connectionUrl: "http://111.111.111.111:8080"

# Make Melody use a custom YouTube cookie when making requests.
# This can help to prevent against receiving 429 rate limits from YouTube.
# See https://github.com/NerdyTechy/Melody/wiki/YouTube-Cookies
cookies:
    useCustomCookie: false
    youtubeCookie: ""
