# This workflow is ran only on pushes to main. It builds the project artifact and deploys it to Google Cloud Compute Engine.
# It also generates releases and tags the commits.

name: deploy

on:
  push:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/prod.yml'
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - '.gitmodules'
    branches: [ 'main' ]

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: aztebot-vm
  GCE_INSTANCE_ZONE: europe-west2-c # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  IMAGE: main
  REPOSITORY: aztebot-docker-ar # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
     contents: 'read'
     id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/536817072469/locations/global/workloadIdentityPools/gh-identity-pool/providers/gh-provider-aztebot'
          service_account: 'gcp-github-access@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
      
      - name: Test Step
        run: echo "oauth2accesstoken::${{ steps.auth.outputs.access_token }}"
      
      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.GCE_INSTANCE_ZONE }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Docker build'
        run: |
          docker build --tag "${{ env.GCE_INSTANCE_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/bot-service/Dockerfile .

      - name: 'Docker push'
        run: |
         docker push "${{ env.GCE_INSTANCE_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"