# This workflow is ran on all PRs and pushes to main. It builds the project and runs the automated tests.
# In the future it could also build and push the containers to the Google Container Registry.

name: test

on:
  pull_request:
  workflow_call:

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |
          : # Environment variables for CI testing
          echo ${{ secrets.CI_ENV_BASE64_STRING }} | base64 --decode > .env

          : # Docker networks for CI testing
          docker network create dev_network
      
      - name: Run CI tests
        run: |
          make ci